FROM node:20

WORKDIR /app

#HEALTHCHECK --interval=30s --timeout=3s \
#  CMD curl -f http://localhost:3000/api/core/version || exit 1

COPY . .

#RUN yarn install
CMD ["yarn", "workspace", "grouping-core", "run", "serve"]
